export const GalleryCategories = [
  { image: () => import('../../components/Gallery/GalleryImages/DSC02929.png'), alt: "pic1" },
  { image: () => import('../../components/Gallery/GalleryImages/AdityaHassan.png'), alt: "pic2" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03002.png'), alt: "pic3" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03255.png'), alt: "pic4" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03270.png'), alt: "pic5" },
  { image: () => import('../../components/Gallery/GalleryImages/durgaglk.png'), alt: "pic6" },
  { image: () => import('../../components/Gallery/GalleryImages/TEDx Stage photo.png'), alt: "pic7" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03003.png'), alt: "pic8" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03208.png'), alt: "pic9" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03220.png'), alt: "pic10" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03501.png'), alt: "pic11" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03527.png'), alt: "pic12" },
  { image: () => import('../../components/Gallery/GalleryImages/DSC03539.png'), alt: "pic13" },
  { image: () => import('../../components/Gallery/GalleryImages/IMG_5447.png'), alt: "pic15" },
  { image: () => import('../../components/Gallery/GalleryImages/IMG_5217.png'), alt: "pic16" },
  { image: () => import('../../components/Gallery/GalleryImages/IMG_5190.png'), alt: "pic17" },
];
